#!/usr/bin/env python3
"""Generate source/PrayerCalcTest.mc from fixtures.txt.

A representative subset of the adhango reference cases (every method for
Istanbul on one date, plus every place/date for Diyanet and the
high-latitude/southern cases) becomes Monkey C unit tests that run in the
Connect IQ simulator:

    monkeyc -d fr265s -f monkey.jungle -o bin/test.prg -y developer_key.der -t
    monkeydo bin/test.prg fr265s -t
"""
import sys
from collections import defaultdict

METHOD_NAMES = ["diyanet", "mwl", "isna", "umm_al_qura", "egyptian", "karachi",
                "moonsighting", "kuwait", "qatar", "singapore", "uoif", "dubai"]


def load(path):
    cases = []
    with open(path) as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            p = line.split()
            cases.append({
                "name": p[0], "y": int(p[1]), "m": int(p[2]), "d": int(p[3]),
                "lat": p[4], "lon": p[5], "mi": int(p[6]), "madhab": int(p[7]),
                "exp": [int(x) for x in p[8:14]],
            })
    return cases


def select(cases):
    keep = []
    for c in cases:
        place = c["name"].split("_")[0]
        if place == "Istanbul" and c["y"] == 2026 and c["m"] == 9:
            keep.append(c)          # every method, both madhabs
        elif c["mi"] == 0 and c["madhab"] == 0:
            keep.append(c)          # Diyanet everywhere, every date
        elif place in ("Oslo", "London", "Sydney") and c["mi"] in (1, 6):
            keep.append(c)          # high-latitude and southern rules
    return keep


def main(fixtures, out):
    cases = select(load(fixtures))
    groups = defaultdict(list)
    for c in cases:
        groups[c["name"].split("_")[0]].append(c)

    lines = [
        "import Toybox.Lang;",
        "import Toybox.Test;",
        "",
        "// GENERATED by tools/verify/gen_tests.py from tools/verify/fixtures.txt",
        "// (adhango reference output). Do not edit by hand.",
        "//",
        "// Each row: [year, month, day, lat, lon, method, madhab, fajr, sunrise,",
        "// dhuhr, asr, maghrib, isha] with times as UTC epoch seconds.",
        "(:test)",
        "module PrayerCalcTest {",
        "",
        "    function check(logger as Test.Logger, rows as Array) as Boolean {",
        "        var ok = true;",
        "        for (var i = 0; i < rows.size(); i++) {",
        "            var r = rows[i] as Array;",
        "            var p = Methods.params(r[5] as Number, r[6] as Number);",
        "            var got = PrayerCalc.compute(r[0] as Number, r[1] as Number, r[2] as Number,",
        "                r[3] as Double, r[4] as Double, p);",
        "            if (got == null) {",
        "                logger.error(Lang.format(\"row $1$: got null\", [i]));",
        "                ok = false;",
        "                continue;",
        "            }",
        "            for (var j = 0; j < 6; j++) {",
        "                var exp = r[7 + j] as Number;",
        "                if (got[j] != exp) {",
        "                    logger.error(Lang.format(\"row $1$ ($2$-$3$-$4$ method $5$) prayer $6$: expected $7$ got $8$ (diff $9$ s)\",",
        "                        [i, r[0], r[1], r[2], r[5], j, exp, got[j], got[j] - exp]));",
        "                    ok = false;",
        "                }",
        "            }",
        "        }",
        "        return ok;",
        "    }",
    ]

    for place in sorted(groups):
        rows = groups[place]
        lines.append("")
        lines.append("    (:test)")
        lines.append(f"    function test{place}(logger as Test.Logger) as Boolean {{")
        lines.append("        return check(logger, [")
        for i, c in enumerate(rows):
            comma = "," if i < len(rows) - 1 else ""
            exp = ", ".join(str(x) for x in c["exp"])
            lines.append(
                f"            [{c['y']}, {c['m']}, {c['d']}, {c['lat']}d, {c['lon']}d, "
                f"{c['mi']}, {c['madhab']}, {exp}]{comma} // {METHOD_NAMES[c['mi']]}")
        lines.append("        ]);")
        lines.append("    }")

    lines.append("}")
    lines.append("")
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"{len(cases)} cases in {len(groups)} tests -> {out}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "tools/verify/fixtures.txt",
         sys.argv[2] if len(sys.argv) > 2 else "source/PrayerCalcTest.mc")
